//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NetProtector.rc
//
#define IDR_TRAYMENU                    4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_APPNAME                     102
#define IDD_NETPROTECTOR                102
#define IDS_APPERROR                    103
#define IDD_OPTIONPAGE                  103
#define IDS_PATH                        104
#define IDS_SRCIP                       107
#define IDD_PROCESSMONITORPAGE          108
#define IDS_DESTIP                      108
#define IDS_SRCPORT                     109
#define IDS_DESTPORT                    110
#define IDS_PROTOCOL                    111
#define IDD_FIREWALLPAGE                111
#define IDS_ACTION                      112
#define IDS_NAME                        113
#define IDD_PROCESSMONITORQUERYDIALOG   114
#define IDD_ADDAPPRULEDLG               115
#define IDR_MAINFRAME                   128
#define IDB_SHIELD                      140
#define IDB_WAREA_UP                    148
#define IDB_WAREA_UP_RIGHT              149
#define IDB_WAREA_RIGHT                 150
#define IDB_WAREA_DOWN_RIGHT            151
#define IDB_WAREA_DOWN                  152
#define IDB_WAREA_DOWN_LEFT             153
#define IDB_WAREA_LEFT                  154
#define IDB_FIREWALLBUTTON_UP           158
#define IDB_FIREWALLBUTTON_DOWN         159
#define IDB_PMONITORBUTTON_UP           160
#define IDB_PMONITORBUTTON_DOWN         161
#define IDB_OPTIONSBUTTON_UP            162
#define IDB_OPTIONSBUTTON_DOWN          163
#define IDB_STATUS_DOWN                 164
#define IDB_STATUS_LEFT                 165
#define IDB_STATUS_RIGHT                166
#define IDB_STATUS_UP                   167
#define IDB_TITLE                       168
#define IDD_ADDRULEDIALOG               169
#define IDR_IPMENU                      171
#define IDR_PORTMENU                    172
#define IDR_ACTIONMENU                  174
#define IDB_FIRE_TITLE                  176
#define IDB_PM_TITLE                    177
#define IDB_OPT_TITLE                   178
#define IDI_BUT_ADD                     184
#define IDI_BUT_DEL                     185
#define IDI_BUT_DELALL                  187
#define IDI_BUT_EDIT                    188
#define IDI_CHECK_ON                    189
#define IDI_CHECK_OFF                   190
#define IDC_RADIO_FIREWALL_ON           1019
#define IDC_RADIO_FIREWALL_OFF          1020
#define IDC_RADIO_PMON_ON               1021
#define IDC_RADIO_PMON_OFF              1022
#define IDC_RULELIST                    1026
#define IDC_BUTTONADD                   1027
#define IDC_BUTTONDELETE                1028
#define IDC_BUTTONEDIT                  1029
#define IDC_BUTTONDELETEALL             1030
#define IDC_GUIDE                       1041
#define IDC_LOGO                        1043
#define IDC_FIREWALLBTN                 1046
#define IDC_PMONBTN                     1047
#define IDC_OPTIONSBTN                  1048
#define IDC_WAREA_LEFT                  1049
#define IDC_STATUS                      1050
#define IDC_SYSINFO_OS                  1054
#define IDC_SYSINFO_CPU                 1055
#define IDC_SYSINFO_MEM                 1056
#define IDC_DESTIP                      1058
#define IDC_HAND2                       1058
#define IDC_SRCPORT                     1059
#define IDC_DESTPORT                    1060
#define IDC_SRCIP                       1061
#define IDC_PROTO                       1063
#define IDC_BUTTON_SRCIP_POPUP          1064
#define IDC_BUTTON_DESTIP_POPUP         1065
#define IDC_THIS_SESSION_ONLY           1065
#define IDC_BUTTON_SRCPORT_POPUP        1066
#define IDC_QUERRY                      1066
#define IDC_BUTTON_DESTPORT_POPUP       1067
#define IDC_QUERRY_NAME                 1067
#define IDC_RULELIST_PM                 1067
#define IDC_QUERRY_PATH                 1068
#define IDC_BUTTONADD_PM                1068
#define IDC_QUERRY_PUBLISHER            1069
#define IDC_BUTTONDELETE_PM             1070
#define IDC_QUERRY_DESCRIPTION          1070
#define IDC_BUTTONDELETEALL_PM          1071
#define IDC_PATH_EDIT                   1073
#define IDC_BROWSE_BUTTON               1074
#define IDC_ACTION_COMBO                1076
#define IDC_APPICON                     1077
#define IDC_PFR_STATIC                  1078
#define IDC_APPRUL_STATIC               1079
#define IDC_SESSIONRUL_STATIC           1080
#define IDC_SESSIONRUL_STATIC2          1081
#define IDC_START_BOOT                  1081
#define IDC_ENABLE_FIRE                 1082
#define IDC_ENABLE_PM                   1083
#define IDC_STATIC_NP                   1084
#define IDC_STATIC_FI                   1085
#define IDC_STATIC_PM                   1086
#define ID_EXIT_ABOUT                   32771
#define ID_POPUP_SHOWNETPROTECTOR       32772
#define ID_POPUP_FIREWALL               32773
#define ID_POPUP_PROCESSMONITOR         32774
#define ID_POPUP_EXIT                   32775
#define ID_POPUP_IP_MYMACHINE           32778
#define ID_POPUP_IP_ANYMACHINE          32779
#define ID_POPUP_ANYPORT                32780
#define ID_POPUP_HTTP                   32781
#define ID_POPUP_FTP                    32782
#define ID_POPUP_SSH                    32783
#define ID_POPUP_TELNET                 32784
#define ID_POPUP_SMTP                   32785
#define ID_POPUP_DNS                    32786
#define ID_POPUP_DHCP                   32787
#define ID_POPUP_POP3                   32788
#define ID_POPUP_NNTP                   32789
#define ID_POPUP_NETBIOS                32790
#define ID_POPUP_SOCKS                  32791
#define ID_POPUP_ALLOW                  32792
#define ID_POPUP_BLOCK                  32793
#define ID_POPUP_APPLICATIONINFO        32794
#define ID_POPUP_HIDE                   32795
#define ID_POPUP_HIDENETPROTECTOR       32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           116
#endif
#endif
