application: howmuchispend
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- datastore_admin: on

handlers:
- url: /favicon\.ico
  static_files: static\img/favicon.ico
  upload: static\img/favicon.ico
  
- url: /static
  static_dir: static

- url: .*
  script: main.py
